// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Container: typeof import('./src/components/layouts/Container.vue')['default']
    DiscordLoginButton: typeof import('./src/components/DiscordLoginButton.vue')['default']
    GuildCard: typeof import('./src/components/GuildCard.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    PlayButton: typeof import('./src/components/PlayButton.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    Profile: typeof import('./src/components/Profile.vue')['default']
    ProgressBar: typeof import('./src/components/ProgressBar.vue')['default']
    Section: typeof import('./src/components/layouts/Section.vue')['default']
    SkipButton: typeof import('./src/components/SkipButton.vue')['default']
    StopButton: typeof import('./src/components/StopButton.vue')['default']
    Tilt: typeof import('./src/components/Tilt.vue')['default']
    VideoResult: typeof import('./src/components/VideoResult.vue')['default']
    Waves: typeof import('./src/components/Waves.vue')['default']
  }
}

export { }
